package es.ubu.lsi.ubumonitor.view.chart;

public enum ChartType {
	HEAT_MAP, STACKED_BAR, LINE, RADAR, GRADE_REPORT_TABLE, CUM_LINE, MEAN_DIFF, ACTIVITIES_TABLE, CALIFICATION_BAR,
	VIOLIN, BOXPLOT, SCATTER, TOTAL_BAR, SCATTER_USER, SESSION, BUBBLE;
}