package es.ubu.lsi.ubumonitor.sigma.model;

public enum AutonomousCommunity {
	ANDALUSIA,
	ARAGON,
	ASTURIAS,
	BALEARIC_ISLANDS,
	BASQUE_COUNTRY,
	CANARY_ISLANDS,
	CANTABRIA,
	CASTILE_AND_LEON,
	CASTILLA_LA_MANCHA,
	CATALONIA,
	COMMUNITY_OF_MADRID,
	EXTREMADURA,
	GALICIA,
	LA_RIOJA,
	NAVARRE,
	REGION_OF_MURCIA,
	VALENCIAN_COMMUNITY,
	CEUTA,
	MELILLA, 
	UNKNOWN;
}
