package controllers.charts;

public enum ChartType {
	HEAT_MAP, STACKED_BAR, LINE, RADAR, GENERAL_BOXPLOT, GRADE_REPORT_TABLE, CUM_LINE, MEAN_DIFF, ACTIVITIES_TABLE, CALIFICATION_BAR, VIOLIN, BOXPLOT;
}